name: krave
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences:
  flutter_spinkit:
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  timeago: ^3.6.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  emoji_picker_flutter: ^2.2.0
  file_picker: ^5.2.3
  fluttertoast: ^8.2.7
  swipe_cards: ^2.0.0+1

  google_maps_flutter: ^2.1.1
  geolocator: ^9.0.1
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.0.0
  get: ^4.6.1
  geocoding: ^2.1.0

  mime_type: ^1.0.1
  intl_phone_field: ^3.2.0
#  internet_connection_checker_plus: ^2.5.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/language/
    - assets/icons/
    - assets/images/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic


